name: mock srpm build
author: John Wass
description: Action for simple chroot building of source RPMs
branding:
  icon: package
  color: red

inputs:
  chroot:
    description: Mock chroot id -- see https://github.com/rpm-software-management/mock/tree/main/mock-core-configs/etc/mock
    required: true
  spec:
    description: Path to spec file
    required: true
  src:
    description: Source file or directory
    required: true
    default: .
  result-dir:
    description: Show mock logs
    required: true
    default: /tmp/mock
  debug:
    description: Show mock logs
    required: false

# mock [options] --buildsrpm {--spec spec --sources src | --scm-enable}

runs:
  using: composite
  steps:
    - id: install-podman
      run: sudo apt install -y podman
      shell: bash

    - id: create-container
      run: |
        mkdir -p ${{ inputs.result-dir }}
        podman run -dt --privileged -v ${{ inputs.src }}:/in -v ${{ inputs.result-dir }}:/out fedora:latest > action.cid
      shell: bash

    - id: init-mock-env
      run: |
        cid=$(cat action.cid)
        podman exec $cid dnf install -y mock
        podman exec $cid mock -r ${{ inputs.chroot }} --init
      shell: bash

    - id: build
      run: |
        cid=$(cat action.cid)
        srpm=$(basename ${{ inputs.srpm }})
        podman cp ${{ inputs.srpm }} $cid:/tmp/$srpm
        podman exec $cid mock -r ${{ inputs.chroot }} buildsrpm --spec ${{ inputs.spec }} --sources /in --resultdir /out
      shell: bash

    - id: show-logs
      if: ${{ inputs.debug }}
      run: |
        cid=$(cat action.cid)
        podman exec $cid ls -R /tmp/rpmbuild
        podman exec $cid cat /tmp/rpmbuild/build.log
      shell: bash
