name: mock srpm build
author: John Wass
description: Action for simple chroot building of source RPMs
branding:
  icon: package
  color: red

inputs:
  chroot:
    description: Mock chroot id -- see https://github.com/rpm-software-management/mock/tree/main/mock-core-configs/etc/mock
    required: true
  spec:
    description: Path to spec file
    required: true
  src:
    description: Path (file or dir) mapped to the rpmbuild/SOURCES directory
    required: false
  result-dir:
    description: Show mock logs
    required: true
    default: .

runs:
  using: composite
  steps:
    - id: install-podman
      run: sudo apt install -y podman
      shell: bash

    - id: prep-fs
      run: |
        touch /tmp/mock-container-args
        mkdir -p ${{ inputs.result-dir }}
      shell: bash

    - id: map-source
      if: inputs.src != null
      run: |
        src="${{ inputs.src }}"
        if [[ "$src" != /* ]]; then src="${{ github.workspace }}/$src"; fi 
        if [[ -d ${src} ]]; then
          arg="-v $src:/in:ro"
        elif [[ -f ${src} ]]; then
          fname=$(basename "${src}")
          arg="-v $src:/in/$fname:ro"
        else
          echo "$src does not exist"
          exit 1
        fi
        echo -n "$arg" > /tmp/mock-container-args
      shell: bash

    - id: create-container
      run: podman run -dt --privileged $(cat /tmp/mock-container-args) -v ${{ inputs.result-dir }}:/out fedora:latest > action.cid
      shell: bash

    - id: init-mock-env
      run: |
        cid=$(cat action.cid)
        podman exec $cid dnf install -y mock
        podman exec $cid mock -r ${{ inputs.chroot }} --init
      shell: bash

    - id: build
      run: |
        cid=$(cat action.cid)
        spec=$(basename ${{ inputs.spec }})
        podman cp ${{ inputs.spec }} $cid:/tmp/$spec
        podman exec $cid mock -r ${{ inputs.chroot }} --copyin /tmp/$spec /builddir/build/SPECS
        podman exec $cid -w / mock -r ${{ inputs.chroot }} --copyin in/ /builddir/build/SOURCES || true
        podman exec $cid ls -alR /var/lib/mock/fedora-39-x86_64/root/builddir/build/SOURCES
        podman exec $cid mock -r ${{ inputs.chroot }} --shell rpmbuild -bs /builddir/build/SPECS/$spec
        podman exec $cid mock -r ${{ inputs.chroot }} --copyout /builddir/build/SRPMS/* /out
      shell: bash
