name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  srpm:
    name: Build srpm
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v4
      - run: |
          dnf install -y rpmdevtools
          mkdir -p /tmp/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          rpmbuild -bs -D "_topdir /tmp/rpmbuild" simple.spec
        working-directory: test/simple
      - name: Checksum artifacts
        run: sha256sum /tmp/rpmbuild/SRPMS/*.src.rpm
      - name: Upload srpm
        uses: actions/upload-artifact@v3
        with:
          name: srpm-artifacts
          path: |
            /tmp/rpmbuild/SRPMS/*

  rpm:
    needs: [ srpm ]
    name: Build rpm with mock-rpm action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download srpm
        uses: actions/download-artifact@v3
        with:
          name: srpm-artifacts
          path: /tmp/src
      - name: Checksum artifacts
        run: sha256sum /tmp/src/*.src.rpm
      - uses: ./
        with:
          chroot: fedora-39-x86_64
          srpm: /tmp/src/simple-0.0.0-1.fc39.src.rpm
          debug: true
      - name: Checksum artifacts
        run: sha256sum /tmp/mock/*
      - name: Upload rpm
        uses: actions/upload-artifact@v3
        with:
          name: rpm-artifacts
          path: |
            /tmp/mock/*.rpm

  it:
    needs: [ rpm ]
    name: Integration test rpm
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - name: Download rpm
        uses: actions/download-artifact@v3
        with:
          name: rpm-artifacts
          path: /tmp/src
      - name: Checksum artifacts
        run: sha256sum /tmp/src/*
      - name: Install rpm
        run: dnf install -y /tmp/src/simple-0.0.0-1.fc39.x86_64.rpm
      - name: Test
        run: simple
