name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rpm:
    name: Build rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build srpm
        uses: ./
        with:
          chroot: fedora-39-x86_64
          spec: test/simple/simple.spec
          debug: true
      - name: Build rpm
        uses: ./hack/mock-rpm
        with:
          chroot: fedora-39-x86_64
          srpm: /tmp/mock/simple-0.0.0.fc39.src.rpm
      - name: Checksum artifacts
        run: sha256sum /tmp/mock/*
      - name: Upload rpm
        uses: actions/upload-artifact@v3
        with:
          name: rpm-artifacts
          path: |
            /tmp/mock/*.rpm

  it:
    needs: [ rpm ]
    name: Integration test rpm
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - name: Download rpm
        uses: actions/download-artifact@v3
        with:
          name: rpm-artifacts
          path: /tmp/src
      - name: Checksum artifacts
        run: sha256sum /tmp/src/*
      - name: Install rpm
        run: dnf install -y /tmp/src/simple-0.0.0-1.fc39.x86_64.rpm
      - name: Test
        run: simple
