name: CI (with dir sources)

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dir-sources:
    name: Build rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build srpm
        uses: ./
        with:
          chroot: fedora-39-x86_64
          spec: test/simple/simple.spec
          src: test/with-sources
      - name: Build rpm
        uses: jw3/mock-rpm@v0
        with:
          chroot: fedora-39-x86_64
          srpm: simple-*.src.rpm
      - uses: actions/upload-artifact@v3
        with:
          name: rpm-artifacts
          path: |
            /tmp/mock/*.rpm

  file-sources:
    name: Build rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build srpm
        uses: ./
        with:
          chroot: fedora-39-x86_64
          spec: test/simple/simple.spec
          src: test/with-sources/withsources.tar.gz
      - name: Build rpm
        uses: jw3/mock-rpm@v0
        with:
          chroot: fedora-39-x86_64
          srpm: simple-*.src.rpm
      - uses: actions/upload-artifact@v3
        with:
          name: rpm-artifacts
          path: |
            /tmp/mock/*.rpm
